create database customer_behavior;
use customer_behavior;
select * from customers;

#----------01. what is the total revenue generated by male v/s female customers
select gender, sum(purchase_amount) as revenue from customers
group by gender;

#----------02.which customers used a discount but still spent more than the avg purchase amount
select customer_id,purchase_amount from customers
where discount_applied="Yes" and purchase_amount>=(select AVG(purchase_amount) from customers);

#----------03.which are the top 5 products with the highest average review rating
select item_purchased,round(avg(review_rating),2) as avg_review_rating from customers
group by item_purchased
order by avg(review_rating) desc
limit 5;
#----------04.compare the avg purchase amount b/w standard and express shipping
select shipping_type,round(avg(purchase_amount),2) from customers
where shipping_type in ("Standard","Express")
group by shipping_type;

#----------05.do subscribed customer spend more? compare avg spend and total revenue
select subscription_status,count(customer_id) as total_customers,round(avg(purchase_amount),2) as avg_spent,round(sum(purchase_amount),2) as total_revenue
from customers
group by subscription_status
order by round(avg(purchase_amount),2),round(sum(purchase_amount),2) desc;

#----------06.which 5 products have the highest percentages of purchases with discount applied
select item_purchased ,
round(100*sum(case when discount_applied="Yes" Then 1 Else 0 end)/count(*),2)as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;

#----------07. segment customers into new,returning,and loyal based on their total number of previus purchases ,and show the 
# count of each segment
with customer_type as( 
select customer_id,previous_purchases,
case
     when previous_purchases=1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
     else 'Loyal'
end as customer_segment
from customers)
select customer_segment,count(*) as 'no_of_customers'
from customer_type
group by customer_segment;

#-------------08. what are the top 3 most purchased products within each category
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customers
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

#--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

#--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customers
GROUP BY age_group
ORDER BY total_revenue desc;

